version: "3.5"
services:
  database:
    restart: always
    image: postgres:10.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=read
    ports:
      - '5433:5432'
    volumes:
      - ./read:/var/lib/postgresql/data
  read:
    restart: always
    build:
      context: .
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/read
    entrypoint: ["sh", "start_api.sh"]

